version: '3'
services:
    nginx:
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "/web/public:${HOME_DIR}"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "8000:80"
            - "8443:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: on-failure
        depends_on:
            - php
    php:
        image: vdzhorov/php-fpm:${PHP_VERSION}
        restart: on-failure
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web/public:${HOME_DIR}"
        env_file:
            - '.env'
    composer:
        image: "composer"
        restart: 'on-failure'
        volumes:
            - "./web/app:/app"
        command: install
        environment:
            - COMPOSER_ALLOW_SUPERUSER=${COMPOSER_ALLOW_SUPERUSER}
    mysql:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: 'on-failure'
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8806:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: 'on-failure'
        env_file:
            - ".env"
        environment:
            - PMA_HOST=${PMA_HOST}
            - PMA_ARBITRARY=${PMA_ARBITRARY}
        ports:
            - "8080:80"
